// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.22.2";

// src/lib/mcp/tools/get-profile.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.2";
var get_profile_default = defineTool({
  name: "get_profile",
  title: "Get profile",
  description: "Returns Janagabalan R's profile: name, title, location, education, and short bio.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [
      {
        type: "text",
        text: JSON.stringify(
          {
            name: "Janagabalan R",
            title: "IoT Enthusiast & ECE Student",
            tagline: "Building Smart Solutions for a Smarter World",
            location: "Tittakudi, Cuddalore District, Tamil Nadu, India",
            education: {
              degree: "B.E. Electronics and Communication Engineering",
              institution: "Dhanalakshmi Srinivasan Engineering College (Autonomous), Perambalur",
              period: "2022 - 2026",
              status: "Currently Pursuing"
            },
            schooling: {
              school: "Sathya Saai Public School CBSE, Pasar",
              grades: "4th - 12th"
            },
            focus: [
              "IoT (Internet of Things)",
              "Arduino / ESP8266 development",
              "Home automation",
              "Cloud platforms: Blynk IoT, Sinric Pro, Google Home"
            ]
          },
          null,
          2
        )
      }
    ]
  })
});

// src/lib/mcp/tools/list-projects.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z } from "npm:zod@^4.4.3";
var projects = [
  {
    id: "smart-home-gemini",
    title: "Smart Home Automation with Gemini",
    description: "Voice-controlled appliances using Gemini AI and Google Home integration for seamless home automation.",
    category: "major",
    tech: ["ESP8266", "Google Home", "Gemini AI", "Blynk IoT"],
    status: "Completed",
    link: "https://www.linkedin.com/posts/janagabalan-r-a72499281_iot-smarthome-googleassistant-activity-7341707262932963329-ULRI"
  },
  {
    id: "smart-door-lock",
    title: "Smart Door Lock with RFID & Remote Control",
    description: "Advanced RFID security system with admin override capabilities and remote access control.",
    category: "major",
    tech: ["Arduino", "RFID", "ESP8266", "Mobile App"],
    status: "Completed"
  },
  {
    id: "radar-ultrasonic",
    title: "Radar System using Ultrasonic Sensor",
    description: "Object detection and tracking system with servo motor integration for automated surveillance.",
    category: "major",
    tech: ["Arduino", "Ultrasonic Sensor", "Servo Motor", "Processing"],
    status: "Completed"
  },
  {
    id: "fire-detection",
    title: "Fire Detection System",
    description: "Smoke sensor-based alert system with immediate notification capabilities for fire safety.",
    category: "minor",
    tech: ["Arduino", "Smoke Sensor", "Buzzer", "LED Indicators"],
    status: "Completed"
  },
  {
    id: "temperature-monitoring",
    title: "Temperature Monitoring System",
    description: "Real-time environmental monitoring with cloud data logging and analytics dashboard.",
    category: "minor",
    tech: ["ESP8266", "DHT22", "Blynk IoT", "Data Analytics"],
    status: "Completed"
  },
  {
    id: "plant-stress-health",
    title: "IoT Framework for Plant Stress & Health",
    description: "Real-time monitoring of plant health with a health score displayed on OLED display and Blynk app for remote tracking.",
    category: "major",
    tech: ["ESP8266", "Sensors", "OLED Display", "Blynk IoT"],
    status: "Completed",
    link: "https://www.linkedin.com/posts/janagabalan-r-a72499281_iot-framework-for-decoding-plant-stress-activity-7396017845630877696-hS4o"
  }
];
var list_projects_default = defineTool2({
  name: "list_projects",
  title: "List projects",
  description: "Lists Janagabalan's IoT projects. Optionally filter by category ('major' or 'minor').",
  inputSchema: {
    category: z.enum(["major", "minor"]).optional().describe("Optional filter: 'major' or 'minor' projects only.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ category }) => {
    const filtered = category ? projects.filter((p) => p.category === category) : projects;
    return {
      content: [{ type: "text", text: JSON.stringify(filtered, null, 2) }]
    };
  }
});

// src/lib/mcp/tools/list-skills.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.2";
var list_skills_default = defineTool3({
  name: "list_skills",
  title: "List skills",
  description: "Returns Janagabalan's technical and professional skills grouped by category.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [
      {
        type: "text",
        text: JSON.stringify(
          {
            "Programming & Development": [
              "Arduino IDE Programming",
              "Basic Python",
              "C Programming",
              "Circuit Debugging"
            ],
            "IoT & Hardware": [
              "ESP8266 Development",
              "Hardware Troubleshooting",
              "Sensor Integration",
              "RFID Systems"
            ],
            "Cloud Platforms": [
              "Blynk IoT",
              "Sinric Pro",
              "Google Home Integration",
              "Data Analytics"
            ],
            "Professional Skills": [
              "Project Documentation",
              "Presentation Skills",
              "Excel Data Entry",
              "Problem Solving"
            ]
          },
          null,
          2
        )
      }
    ]
  })
});

// src/lib/mcp/tools/list-services.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.22.2";
var list_services_default = defineTool4({
  name: "list_services",
  title: "List services",
  description: "Returns the IoT services and solutions Janagabalan offers.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [
      {
        type: "text",
        text: JSON.stringify(
          [
            {
              title: "Home Automation Systems",
              description: "Smart home solutions with voice control using Google Home and Gemini AI.",
              features: ["Voice Control", "Remote Access", "Energy Monitoring", "Custom Scheduling"]
            },
            {
              title: "Smart Security Systems",
              description: "RFID-based security systems with admin controls and remote monitoring.",
              features: ["RFID Access Control", "Admin Override", "Remote Monitoring", "Alert Systems"]
            },
            {
              title: "Sensor-Based Alerting",
              description: "Ultrasonic and radar systems for object detection and tracking.",
              features: ["Object Detection", "Real-time Tracking", "Automated Alerts", "Data Logging"]
            },
            {
              title: "Environmental Monitoring",
              description: "Real-time temperature and environmental monitoring with cloud integration.",
              features: ["Real-time Monitoring", "Cloud Integration", "Data Analytics", "Historical Trends"]
            },
            {
              title: "Safety & Fire Detection",
              description: "Smoke sensor-based fire detection with immediate alert capabilities.",
              features: ["Smoke Detection", "Immediate Alerts", "Emergency Protocols", "Multi-sensor Integration"]
            },
            {
              title: "Project Consulting",
              description: "IoT consultation and prototyping services for custom solutions.",
              features: ["Custom Solutions", "Rapid Prototyping", "Technical Consultation", "Implementation Support"]
            }
          ],
          null,
          2
        )
      }
    ]
  })
});

// src/lib/mcp/tools/get-contact.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.22.2";
var get_contact_default = defineTool5({
  name: "get_contact",
  title: "Get contact info",
  description: "Returns public contact information for Janagabalan R.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [
      {
        type: "text",
        text: JSON.stringify(
          {
            email: "janagabalanr@gmail.com",
            phone: "+91 8610453552",
            location: "Tittakudi, Cuddalore District, Tamil Nadu, India",
            linkedin: "https://www.linkedin.com/in/janagabalan-r-a72499281",
            portfolio: "https://janagabalan.netlify.app"
          },
          null,
          2
        )
      }
    ]
  })
});

// src/lib/mcp/tools/list-internships.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.22.2";
var list_internships_default = defineTool6({
  name: "list_internships",
  title: "List internships",
  description: "Returns Janagabalan's internship experience with company, role, and dates.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [
      {
        type: "text",
        text: JSON.stringify(
          [
            {
              company: "NSIC, Chennai",
              role: "IoT Training",
              duration: "1 week",
              date: "August 2024",
              description: "Gained hands-on experience in IoT technologies and industrial applications."
            },
            {
              company: "ALAS Robotech Solution, Salem",
              role: "Robotics and IoT",
              duration: "10 days",
              date: "February 2025",
              description: "Advanced training in robotics integration with IoT systems."
            }
          ],
          null,
          2
        )
      }
    ]
  })
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "janagabalan-portfolio-mcp",
  title: "Janagabalan Portfolio MCP",
  version: "0.1.0",
  instructions: "Public MCP server for Janagabalan R's IoT portfolio. Use these tools to look up his profile, IoT projects, skills, services offered, internship experience, and public contact info.",
  tools: [get_profile_default, list_projects_default, list_skills_default, list_services_default, get_contact_default, list_internships_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
